# Generated by Django 2.1.3 on 2018-12-21 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='items',
        ),
        migrations.AddField(
            model_name='order',
            name='items',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='ecomapp.Cart'),
        ),
        migrations.AlterField(
            model_name='service',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecomapp.Brand'),
        ),
    ]
